### ISSUE TITLE
Github shows java tag even tho nothing there

### ISSUE THREAD

**Issue by mTvare6** [IGSQ/IGSQ-Bot#3]
![image](https://user-images.githubusercontent.com/57838468/104129666-05f25e80-5393-11eb-9f8f-48d184d88d3f.png)
see it shows java even tho there is nothing

**Comment by arynxd** [comment]
Are you viewing the right branch?

**Comment by mTvare6** [comment]
ah seems I was looking at default branch


the default branch is empty







make sure to change




thx
